@echo off
cd frontend
echo Installing base dependencies...
call npm install
echo Installing Tailwind CSS...
call npm install -D tailwindcss postcss autoprefixer
echo Initializing Tailwind...
call npx tailwindcss init -p
echo Installing UI libraries...
call npm install react-router-dom axios lucide-react date-fns clsx tailwind-merge framer-motion
echo Done!
