"""add assignee_id to recurring templates

Revision ID: e10f5816072b
Revises: e60a31302c68
Create Date: 2026-07-17 04:59:26.763925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10f5816072b'
down_revision: Union[str, None] = 'e60a31302c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_task_templates', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recurring_task_templates', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_task_templates', type_='foreignkey')
    op.drop_column('recurring_task_templates', 'assignee_id')
    # ### end Alembic commands ###
